
import java.util.Calendar;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Asus
 */
public class ViewHalamanUtama extends javax.swing.JFrame {
    
    ButtonGroup groupJenis;
    ButtonGroup groupTipe;
    int hitungSaldo = 0;
    /**
     * Creates new form HalamanUtama
     */
    public ViewHalamanUtama() {
        this.groupTipe = new javax.swing.ButtonGroup();
        this.groupJenis = new javax.swing.ButtonGroup();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_pemasukan = new javax.swing.JButton();
        btn_pengeluaran = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_setting = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtab_transaksi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        radioPemasukan = new javax.swing.JRadioButton();
        radioPengeluaran = new javax.swing.JRadioButton();
        radioJenisSemua = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        radioSekali = new javax.swing.JRadioButton();
        radioHarian = new javax.swing.JRadioButton();
        radioMingguan = new javax.swing.JRadioButton();
        radioBulanan = new javax.swing.JRadioButton();
        radioTipeSemua = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        perkiraan = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btn_pemasukan.setText("Tambah Pemasukan");
        btn_pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pemasukanActionPerformed(evt);
            }
        });

        btn_pengeluaran.setText("Tambah Pengeluaran");
        btn_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pengeluaranActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit Transaksi");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        jButton1.setText("Hapus Transaksi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_setting.setText("Setting");
        btn_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_pemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_pengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_pemasukan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_setting)
                .addContainerGap())
        );

        jLabel1.setText("History");

        jtab_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null,null}
            },
            new String [] {
                "Tanggal","Jenis", "Judul", "Deskripsi","Tipe", "Nominal"
            }
        ){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        jScrollPane1.setViewportView(jtab_transaksi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 779, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );

        jPanel3.setToolTipText("Search");
        jPanel3.setPreferredSize(new java.awt.Dimension(1004, 248));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pengatur Keuangan Mahasiswa");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis");

        radioPemasukan.setText("Pemasukan");
        radioPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPemasukanActionPerformed(evt);
            }
        });

        radioPengeluaran.setText("Pengeluaran");
        radioPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPengeluaranActionPerformed(evt);
            }
        });

        radioJenisSemua.setText("Semua");
        radioJenisSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioJenisSemuaActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipe");

        radioSekali.setText("Sekali");
        radioSekali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSekaliActionPerformed(evt);
            }
        });

        radioHarian.setText("Harian");

        radioMingguan.setText("Mingguan");

        radioBulanan.setText("Bulanan");

        radioTipeSemua.setText("Semua");

        jLabel5.setText("Perkiraan dalam Hari : ");

        jLabel6.setText("Saldo : ");

        perkiraan.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(radioPemasukan)
                                    .addComponent(radioPengeluaran)
                                    .addComponent(radioJenisSemua))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioMingguan)
                                    .addComponent(radioHarian)
                                    .addComponent(radioSekali)
                                    .addComponent(jLabel4)
                                    .addComponent(radioBulanan)
                                    .addComponent(radioTipeSemua)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(perkiraan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(perkiraan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPemasukan)
                    .addComponent(radioSekali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPengeluaran)
                    .addComponent(radioHarian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioJenisSemua)
                    .addComponent(radioMingguan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBulanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioTipeSemua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pemasukanActionPerformed
        // TODO add your handling code here:
        HalamanUtama.btn_tambahPemasukan(this);
        
    }//GEN-LAST:event_btn_pemasukanActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.hitungSaldo=0;
         Model.selectAll(jtab_transaksi);
         for(int i =0;i<jtab_transaksi.getRowCount();i++){
             if(jtab_transaksi.getModel().getValueAt(i, 1).equals("Pengeluaran")){
                 hitungSaldo = hitungSaldo - (Integer)jtab_transaksi.getModel().getValueAt(i, 5);
             }
             else{
                 hitungSaldo = hitungSaldo + (Integer)jtab_transaksi.getModel().getValueAt(i, 5);
             }
         }
         
         saldo.setText(Integer.toString(hitungSaldo));
         Object[] setting = Model.selectSetting();
         Date date= new Date();
         Calendar cal = Calendar.getInstance();
         cal.setTime(date);
         int day = cal.get(Calendar.DATE);
         int jmlDay = cal.getActualMaximum(Calendar.DAY_OF_MONTH);
         int month = cal.get(Calendar.MONTH);
         int year = cal.get(Calendar.YEAR);
         int rata = 0;
         int count = 0;
         System.out.println(jmlDay);
         if("Minggu".equals((String)setting[2])){
             for(int i =0;i<jtab_transaksi.getRowCount();i++){
                String tgl = (String)jtab_transaksi.getModel().getValueAt(i, 0);
                String bulan = tgl.substring(5, 7);
                String tahun = tgl.substring(0,4);
                String hari = tgl.substring(8,10);
                if(day-7 > 0){
                    if("Pengeluaran".equals((String)jtab_transaksi.getModel().getValueAt(i, 1)) && Integer.parseInt(tahun) == year && (month + 1) == Integer.parseInt(bulan) && Integer.parseInt(hari) >= day-7){
                        System.out.println("masuk1");
                        rata = rata + (Integer)jtab_transaksi.getModel().getValueAt(i, 5);
                        count++;
                    }
                }
                else{
                    if("Pengeluaran".equals((String)jtab_transaksi.getModel().getValueAt(i, 1)) && Integer.parseInt(tahun) == year && ((month + 1) - Integer.parseInt(bulan)) == 1 && Integer.parseInt(hari) >= jmlDay - (day-7)){
                        System.out.println("masuk3");
                        rata = rata + (Integer)jtab_transaksi.getModel().getValueAt(i, 5);
                        count++;
                    }
                    if("Pengeluaran".equals((String)jtab_transaksi.getModel().getValueAt(i, 1)) && Integer.parseInt(tahun) == year && ((month + 1) - Integer.parseInt(bulan)) == 0){
                        System.out.println("masuk3");
                        rata = rata + (Integer)jtab_transaksi.getModel().getValueAt(i, 5);
                        count++;
                    }
                }
            }
            System.out.println(rata);
            try{
                rata = hitungSaldo/rata;
                perkiraan.setText(Integer.toString(rata));
            }
            catch(Exception e){
                perkiraan.setText("Error, tidak ada pengeluaran 1 minggu");
            }
            
         }
         else if("Bulan".equals((String)setting[2])){
            for(int i =0;i<jtab_transaksi.getRowCount();i++){
                String tgl = (String)jtab_transaksi.getModel().getValueAt(i, 0);
                String bulan = tgl.substring(5, 7);
                String tahun = tgl.substring(0,4);
                String hari = tgl.substring(8,10);
                if("Pengeluaran".equals((String)jtab_transaksi.getModel().getValueAt(i, 1)) && Integer.parseInt(tahun) == year && Math.abs((month + 1) - Integer.parseInt(bulan)) <= 1){
                    rata = rata + (Integer)jtab_transaksi.getModel().getValueAt(i, 5);
                    count++;
                }
            }
             System.out.println(rata);
            try{
                rata = hitungSaldo/rata;
                perkiraan.setText(Integer.toString(rata));
            }
            catch(Exception e){
                perkiraan.setText("Error, tidak ada pengeluaran 1 bulan");
            }
         }
         else{
             perkiraan.setText("Tidak Memakai Perkiraan");
         }
    }//GEN-LAST:event_formWindowGainedFocus

    private void btn_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pengeluaranActionPerformed
        // TODO add your handling code here:
        HalamanUtama.btn_tambahPengeluaran(this);
    }//GEN-LAST:event_btn_pengeluaranActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        int row_terpilih = jtab_transaksi.getSelectedRow();
        System.out.println(jtab_transaksi.getSelectedColumn());
        String tgl="";
        try{
            tgl = jtab_transaksi.getModel().getValueAt(row_terpilih, 0).toString();
        }catch(Exception e){
        }
        
        HalamanUtama.btn_editTransaksi(this,tgl);
    }//GEN-LAST:event_btn_editActionPerformed

    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                
                return button.getText();
            }
        }

        return null;
    }

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row_terpilih = jtab_transaksi.getSelectedRow();
        String tgl="";
        try{
            tgl = jtab_transaksi.getModel().getValueAt(row_terpilih, 0).toString();
        }catch(Exception e){
        }
        HalamanUtama.btn_hapus(this, tgl);
        Model.selectAll(jtab_transaksi);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settingActionPerformed
        // TODO add your handling code here:
        HalamanUtama.btn_setting(this);
    }//GEN-LAST:event_btn_settingActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String text;
        if (jTextField1.getText() == null){
            text="";
        }
        else{
            text=jTextField1.getText();
        }
        if(radioTipeSemua.isSelected() && radioJenisSemua.isSelected()){
            Search search=new Search(text);
            System.out.println("semuanya");
        }
        else{
            Search search=new Search(text, getSelectedButtonText(groupJenis), getSelectedButtonText(groupTipe));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPemasukanActionPerformed

    private void radioPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPengeluaranActionPerformed

    private void radioJenisSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioJenisSemuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioJenisSemuaActionPerformed

    private void radioSekaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSekaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSekaliActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        groupJenis.add(radioPemasukan);
        groupJenis.add(radioPengeluaran);
        groupJenis.add(radioJenisSemua);
        groupTipe.add(radioBulanan);
        groupTipe.add(radioHarian);
        groupTipe.add(radioMingguan);
        groupTipe.add(radioSekali);
        groupTipe.add(radioTipeSemua);
        radioJenisSemua.setSelected(true);      
        radioTipeSemua.setSelected(true);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_pemasukan;
    private javax.swing.JButton btn_pengeluaran;
    private javax.swing.JButton btn_setting;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtab_transaksi;
    private javax.swing.JLabel perkiraan;
    private javax.swing.JRadioButton radioBulanan;
    private javax.swing.JRadioButton radioHarian;
    private javax.swing.JRadioButton radioJenisSemua;
    private javax.swing.JRadioButton radioMingguan;
    private javax.swing.JRadioButton radioPemasukan;
    private javax.swing.JRadioButton radioPengeluaran;
    private javax.swing.JRadioButton radioSekali;
    private javax.swing.JRadioButton radioTipeSemua;
    private javax.swing.JLabel saldo;
    // End of variables declaration//GEN-END:variables
}
